(()=>{'use strict';
const $=id=>document.getElementById('care-'+id), fmt=x=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:2}).format(x);
const defs={n:50,Q:1130,q:22.6,f:8000,S:400000,FP:1250000,FL:170000,k:300,m:1000,p:800,v:300,safe:10000,lambda:3,e:100,a:100,external:0,margin:10000,days:7,peak:0,hours:40,leave:20};
const fields=[['n','付費診所 n（家，上下同步）',1,200,1],['Q','常態管理 Q（案）',0,100000,1],['q','每家平均 q（案；Q＝round(nq)）',0,10000,'any'],['f','每家月會費 f（元，上下同步）',0,200000,1],['S','經常性月補助 S（元）',0,100000000,1],['FP','平台月成本 FP（元）',0,100000000,'any'],['FL','每在地單元月固定費 FL（元）',0,10000000,1],['k','每單元容量 k（案）',1,100000,1],['m','每案月貢獻 m（元）',-100000,100000,1],['p','模型一每案月收入 p（元）',0,100000,1],['v','模型一每案月變動費 v（元）',0,100000,1],['safe','全網安全服務上限（案）',0,100000,1]];
const af=[['lambda','每月急症發生率 λ（%）',0,100,.1],['e','臨床適合比例 e（%）',0,100,.1],['a','願意且能承接 a（%）',0,100,.1],['external','每月外部轉介（療程）',0,100000,.1],['margin','每療程淨貢獻（元）',-1000000,1000000,1],['days','平均療程天數',.1,365,.1],['peak','尖峰同時量（人；0=未估）',0,100000,1],['hours','每 FTE 每週工時',1,168,1],['leave','休假訓練不可排比例（%）',0,99,1]];
for(const [target,items] of [['fields',fields],['acute-fields',af]]) $(target).innerHTML=items.map(([id,label,min,max,step])=>`<label for="care-${id}">${label}<input id="care-${id}" type="number" min="${min}" max="${max}" step="${step}" value="${defs[id]}"></label>`).join('');
const all=[...fields,...af],key='clinic-care-model-v4';let latest;
function snapshot(){const x={};for(const [id] of all)x[id]=$(id).value;for(const id of ['mode','source','fees','regions'])x[id]=$(id).value;x.add=$('acute-add').checked;return x;}
function restore(x){for(const [id] of all)if(x[id]!==undefined)$(id).value=x[id];for(const id of ['mode','source','fees','regions'])if(x[id]!==undefined)$(id).value=x[id];$('acute-add').checked=!!x.add;if(x.Q!==undefined&&x.n) $('q').value=x.Q/x.n;window.clinicBridge.set({n:Number($('n').value),targetFee:Number($('f').value)});}
try{const saved=JSON.parse(localStorage.getItem(key));restore(saved||{...defs,source:'original',mode:'integrated',fees:'external',regions:'',add:false});}catch{}
function read(){const x={};for(const [id,label,min,max] of all){const v=Number($(id).value);if($(id).value===''||!Number.isFinite(v)||v<min||v>max||!$(id).validity.valid)throw Error('請檢查「'+label+'」的輸入範圍與步進值。');x[id]=v;}x.mode=$('mode').value;x.source=$('source').value;x.fees=$('fees').value;x.add=$('acute-add').checked;x.regions=[];x.n=window.clinicBridge.get().n;x.f=window.clinicBridge.get().fee;if(x.source==='original'&&x.mode!=='local')x.FP=window.clinicBridge.get().budget;
if($('regions').value.trim()){if(x.mode!=='integrated')throw Error('分區配置只適用模型三；切換其他模型前請清空分區資料。');x.regions=$('regions').value.trim().split('\n').map((line,i)=>{const v=line.split(/[,，]/).map(t=>t.trim());if(v.length!==4||v.some(t=>t==='')||v.some(t=>!Number.isFinite(Number(t))))throw Error('分區第 '+(i+1)+' 列需四個數值。');const [Q,k,safe,extra]=v.map(Number);if(!Number.isInteger(Q)||Q<0||!Number.isInteger(k)||k<1||safe<0||extra<0)throw Error('分區個案／容量須為整數且容量大於 0，其餘不得負數。');return {Q,k,safe,extra};});x.Q=x.regions.reduce((s,r)=>s+r.Q,0);if(x.Q>100000)throw Error('分區合計不得超過 100,000 案。');}return x;}
function calc(x,Q=x.Q,n=x.n){const U=x.mode==='integrated'?(x.regions.length?x.regions.reduce((s,r)=>s+Math.ceil(r.Q/r.k),0):Math.ceil(Q/x.k)):x.mode==='local'?1:0;
const E=Q*x.lambda/100*x.e/100*x.a/100+x.external,B=E*x.days/30,acute=x.add?E*x.margin:0;
const fees=x.mode==='local'||x.fees==='internal'?0:n*x.f;
const platform=x.mode==='local'?0:x.FP,local=x.mode==='simple'?0:U*x.FL,extra=x.regions.reduce((s,r)=>s+r.extra,0);
const contribution=Q*(x.mode==='simple'?x.p-x.v:x.m);
return {Q,n,U,E,B,acute,fees,platform,local,extra,contribution,profit:contribution+acute+fees+x.S-platform-local-extra};}
function distribute(regions,Q){const total=regions.reduce((a,r)=>a+r.Q,0);if(!total&&Q)throw Error('分區全為零，無法推估個案比例。');let rows=regions.map((r,i)=>{const ideal=total?Q*r.Q/total:0;return {...r,Q:Math.floor(ideal),fraction:ideal-Math.floor(ideal),i};});let left=Q-rows.reduce((a,r)=>a+r.Q,0);const order=[...rows].sort((a,b)=>b.fraction-a.fraction||a.i-b.i);for(let i=0;i<left;i++)order[i].Q++;return rows;}
function at(x,n=x.n,Q=Math.round(n*x.q)){const FP=x.source==='original'&&x.mode!=='local'?window.clinicBridge.calculate({...window.clinicBridge.current(),n}).budget:x.FP;const xx={...x,n,Q,FP,regions:x.regions.length?distribute(x.regions,Q):[]};const r=calc(xx,Q,n);r.feasible=Q<=x.safe&&(x.mode!=='local'||Q<=x.k)&&xx.regions.every(a=>a.Q<=a.safe);return r;}
function first(x,type){if(type==='Q'&&x.regions.length)return null;for(let i=type==='Q'?0:1;i<=(type==='Q'?100000:200);i++){const Q=type==='Q'?i:Math.round(i*x.q);if(Q>100000)break;const r=type==='Q'?calc(x,Q):at(x,i,Q);if(r.profit>=-1e-8)return i;}return null;}
// Continuous capacity allocation benchmark; not a forecast or executable staffing plan.
function smoothPlatform(n){const v=window.clinicBridge.current(),c=Math.min(v.centers,n),z=n/c,p=v.procurement/100,t=v.it/100,a=v.admin/100,st=v.standard/100,d=v.diversity/100;
const fixed=v.fixedBase+120000*p+160000*t+180000*a+100000*st;
const variable=1500*p+2200*t+5500*a+1200*st+2800*a*st*d*(v.exceptions?1:.4)+3000*t*d*(1-st);
return c*fixed+n*variable+(c*v.setupBase+n*30000*(a+t+st)/3)/v.months+c*v.friction*z*(z-1)+c*Math.max(0,z/v.capacity-1)*v.teamCost;}
function average(x,n=x.n,Q=n*x.q){const total=x.regions.reduce((s,r)=>s+r.Q,0);const units=x.mode==='integrated'?(x.regions.length?x.regions.reduce((s,r)=>s+(total?Q*r.Q/total:0)/r.k,0):Q/x.k):x.mode==='local'?1:0;
const platform=x.mode==='local'?0:x.source==='original'?smoothPlatform(n):x.FP;
const E=Q*x.lambda/100*x.e/100*x.a/100+x.external;
return Q*(x.mode==='simple'?x.p-x.v:x.m)+(x.add?E*x.margin:0)+(x.mode==='local'||x.fees==='internal'?0:n*x.f)+x.S-platform-units*x.FL-x.regions.reduce((s,r)=>s+r.extra,0);}
function dualPlot(points,current,label,ticks){const W=800,H=280,L=70,R=30,T=25,B=45;const vals=points.flatMap(a=>[a.profit,a.avg]);let low=Math.min(0,...vals),high=Math.max(1,...vals);const pad=(high-low)*.08;low-=pad;high+=pad;const start=points[0].axis,end=points.at(-1).axis;const px=n=>L+(n-start)/Math.max(1,end-start)*(W-L-R),py=v=>T+(high-v)/(high-low)*(H-T-B);
const path=key=>points.map((a,i)=>!i?'M'+px(a.axis).toFixed(2)+','+py(a[key]).toFixed(2):key==='profit'?'H'+px(a.axis).toFixed(2)+' V'+py(a[key]).toFixed(2):'L'+px(a.axis).toFixed(2)+','+py(a[key]).toFixed(2)).join(' ');
const grid=[low,low+(high-low)/2,high].map(v=>`<line x1="${L}" x2="${W-R}" y1="${py(v)}" y2="${py(v)}" stroke="#edf0e8"/><text x="${L-9}" y="${py(v)+4}" text-anchor="end" font-size="11" fill="#788b80">${fmt(v/10000)}萬</text>`).join('');
return `<div class="dual-legend"><span><i class="average-line"></i>長期平均趨勢（連續容量估算）</span><span><i class="actual-line"></i>實際整數配置（階梯線）</span></div><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${label}，平滑平均趨勢與實際整數配置雙線"><defs><linearGradient id="dual-fill-${label==='診所數'?'n':'q'}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#dbead4" stop-opacity=".45"/><stop offset="1" stop-color="#f4f7ee" stop-opacity=".05"/></linearGradient></defs>${grid}<line x1="${L}" x2="${W-R}" y1="${py(0)}" y2="${py(0)}" stroke="#9aaea1" stroke-dasharray="4 5"/><path d="${path('avg')} L${px(end)},${py(low)} L${px(start)},${py(low)}Z" fill="url(#dual-fill-${label==='診所數'?'n':'q'})"/><path data-series="average" d="${path('avg')}" fill="none" stroke="#438068" stroke-width="2.8" stroke-linejoin="round"/><path data-series="actual" d="${path('profit')}" fill="none" stroke="#9381af" stroke-width="1.6" stroke-dasharray="4 3" stroke-linejoin="round"/>${points.filter(a=>a.feasible===false).filter((_,i)=>i%4===0).map(a=>`<circle cx="${px(a.axis)}" cy="${py(a.profit)}" r="2" fill="#bf772e"/>`).join('')}<line x1="${px(current.axis)}" x2="${px(current.axis)}" y1="${py(current.profit)}" y2="${py(low)}" stroke="#b6a9c8" stroke-dasharray="3 4"/><circle cx="${px(current.axis)}" cy="${py(current.profit)}" r="5" fill="#796294" stroke="white" stroke-width="2"/>${ticks.filter(n=>n>=start&&n<=end).map(n=>`<text x="${px(n)}" y="${H-18}" text-anchor="middle" font-size="12" fill="#788b80">${fmt(n)}</text>`).join('')}<text x="${W-R}" y="${H-2}" text-anchor="end" font-size="10" fill="#788b80">${label}</text></svg>`;}
function chart(x){if(x.regions.length)return '<p>分區配置啟用：雙線請參考本區的診所規模圖，按各區占比分配個案。</p>';const end=Math.min(100000,Math.ceil(Math.max(1500,x.Q*1.4,x.k*5))),points=[];const stride=Math.max(1,Math.floor(end/1500));const indices=new Set([0,end,x.Q]);for(let Q=0;Q<=end;Q+=stride)indices.add(Q);if(x.mode==='integrated')for(let Q=x.k;Q<=end;Q+=x.k){indices.add(Q);if(Q+1<=end)indices.add(Q+1);}for(const Q of [...indices].sort((a,b)=>a-b))points.push({axis:Q,profit:calc(x,Q).profit,avg:average(x,x.n,Q)});return dualPlot(points,{axis:x.Q,profit:calc(x).profit},'個案數',[0,Math.round(end/2),end]);}
function render(){try{const x=read();if(x.regions.length){x.q=x.Q/x.n;$('q').value=x.q;$('Q').value=x.Q;}const r=at(x,x.n,x.Q),be=first(x,'Q'),bn=x.mode==='local'?null:first(x,'n');latest={x,r,be,bn};$('error').textContent='';const link=x.source==='original'&&x.mode!=='local';$('FP').disabled=link;$('n').disabled=false;$('f').disabled=false;$('n').value=x.n;$('f').value=x.f;if(link)$('FP').value=x.FP;for(const id of ['p','v'])$(id).disabled=x.mode!=='simple';$('m').disabled=x.mode==='simple';for(const id of ['FL','k'])$(id).disabled=x.mode==='simple';$('Q').disabled=x.regions.length>0;
const kpis=[['月損益',fmt(r.profit)+' 元'],['在地單元',r.U+' 個'],['固定診所数：首次打平',x.regions.length?'依分區配置判斷':be===null?'10 萬案內未打平':fmt(be)+' 案'],['Q=nq：首次打平家數',x.mode==='local'?'不適用':bn===null?'200'+' 家內未打平':fmt(bn)+' 家']];
const safe=x.regions.length?x.regions.every(t=>t.Q<=t.safe):x.Q<=x.safe;const next=(Math.floor(x.Q/x.k)+1)*x.k+1;let warn=[];if(!safe)warn.push('目前個案量超過設定的安全服務上限。');if(be!==null&&be>x.safe)warn.push('首次打平需求高於安全服務上限；本情境在安全量能內沒有自給自足解。');if(x.mode==='local'&&x.Q>x.k)warn.push('單一在地單元個案超過 k；損益仍照公式列示，配置不可視為可行。');if(x.mode==='local'&&be!==null&&be>x.k)warn.push('單元首次打平量超過 k，需調整支付或配置。');
let steps='';if(x.mode==='integrated'&&!x.regions.length)steps=`<p>下一次擴充為 ${fmt(next)} 案，需 ${Math.ceil(next/x.k)} 單元，當月損益 ${fmt(calc(x,next).profit)} 元。首次打平不保證後續持續打平。</p>`;
const fte=168/(x.hours*(1-x.leave/100));
$('results').innerHTML=`<div class="care-kpis">${kpis.map(([a,b])=>`<article>${a}<strong>${b}</strong></article>`).join('')}</div><p>${link?`已連動原模型：${x.n} 家、平台預算 ${fmt(x.FP)} 元、每家會費 ${fmt(x.f)} 元。`:'使用報告／手動假設。'}${x.regions.length?'分區合計 '+fmt(x.Q)+' 案。':''}</p><p class="care-warning">${warn.join(' ')}</p><div class="table-scroll"><table><thead><tr><th>收支項目</th><th>金額（元／月）</th></tr></thead><tbody>${[['常態個案貢獻',r.contribution],['計入會費',r.fees],['經常補助',x.S],['加計急症貢獻',r.acute],['平台成本',-r.platform],['在地固定成本',-r.local],['分區增量費',-r.extra],['損益',r.profit]].map(([a,b])=>`<tr><td>${a}</td><td>${fmt(b)}</td></tr>`).join('')}</tbody></table></div>${steps}<p>本區上圖呈現診所規模對在宅損益的影響；以下另顯示固定診所數時的個案敏感度。</p>${chart(x)}<p>急症療程 E：${fmt(r.E)}／月；平均同時量 B：${fmt(r.B)} 人。${x.peak?'設定尖峰 '+fmt(x.peak)+' 人。':'尚未設定尖峰量。'}<br>每一個全年全天候有人值守席位，按所填工時與不可排比例需約 ${fmt(fte)} FTE。這是排班算術，不是法定人力或完整外勤配置。</p><p><small>搜尋允許 Q=0，固定收入可使零案帳面打平，並不表示已提供服務。家數搜尋統一為 1–200 家，Q 按 round(nq) 計算。平台費用為扣除按案變動成本後仍待支應之費用，不能將其除以 Q 稱為完整臨床平均成本。</small></p>`;
draw();try{localStorage.setItem(key,JSON.stringify(snapshot()));}catch{}
}catch(err){$('error').textContent=err.message;$('results').innerHTML='';latest=null;document.getElementById('care-scale-chart').textContent='請修正下方模型輸入後重新計算。';document.getElementById('care-scale-summary').textContent='輸入未完成，暫停顯示結果';document.getElementById('care-scale-threshold').textContent='待計算';}}
$('presets').addEventListener('click',e=>{const i=e.target.dataset.carePreset;if(i===undefined)return;restore({...defs,mode:'integrated',source:'manual',fees:'external',regions:'',add:false,m:+i===0?850:1000,k:+i===0?250:300,f:+i>=2?8000:0,S:+i===3?400000:0,Q:[7471,2950,2040,1130][+i]});render();});
$('simple').onclick=()=>{restore({...defs,mode:'simple',source:'manual',fees:'external',regions:'',add:false,n:20,Q:400,f:10000,S:0,FP:400000});render();};
$('reset').onclick=()=>{restore({...defs,mode:'integrated',source:'original',fees:'external',regions:'',add:false});render();};
function fromCare(event){const id=event.target.id;if(['care-n','care-f'].includes(id)){if(event.target.value===''||!event.target.validity.valid){render();return;}window.clinicBridge.set({n:Number($('n').value),targetFee:Number($('f').value)});return;}if(id==='care-Q'&&$('Q').value!==''&&$('Q').validity.valid)$('q').value=Number($('Q').value)/window.clinicBridge.get().n;if(id==='care-q'&&$('q').value!==''&&$('q').validity.valid)$('Q').value=Math.round(window.clinicBridge.get().n*Number($('q').value));render();}
document.getElementById('care-model').addEventListener('input',fromCare);document.getElementById('care-model').addEventListener('change',fromCare);
window.addEventListener('clinic-model-change',()=>{const n=window.clinicBridge.get().n;const oldN=latest?.x.n||Number($('n').value);if($('regions').value.trim()&&n!==oldN){try{const prev=read();const rows=distribute(prev.regions,Math.round(n*Number($('q').value)));$('regions').value=rows.map(r=>[r.Q,r.k,r.safe,r.extra].join(',')).join('\n');}catch{}}else if(!$('regions').value.trim())$('Q').value=Math.round(n*Number($('q').value));$('n').value=n;$('f').value=window.clinicBridge.get().fee;render();});
$('export').onclick=()=>{if(!latest)return;const {x,r,be,bn}=latest,rows=[['在宅醫療上下連動模型 v4','所有係數為示範假設'],['參數','值'],...Object.entries(x).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):v]),['結果','值'],...Object.entries(r),['首次打平個案',be??'範圍內無解或分區不適用'],['首次打平家數',bn??'無解或不適用']];rows.push([],['在宅損益規模曲線：診所數','個案數','月損益','在地單元','平台成本','安全量能內','長期平均趨勢月損益']);for(let n=1;n<=200;n++){if(Math.round(n*x.q)>100000)break;const a=at(x,n);rows.push([n,a.Q,a.profit,a.U,a.platform,a.feasible,average(x,n)]);}const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='在宅醫療整合模型.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);};
function draw(){if(!latest)return;const {x}=latest,data=[];for(let n=1;n<=200;n++){if(Math.round(n*x.q)>100000)break;const a=at(x,n);data.push({...a,axis:n,avg:average(x,n)});}const be=data.find(a=>a.profit>=-1e-8),shown=at(x,x.n,x.Q),trend=average(x,x.n,x.Q);
document.getElementById('care-scale-threshold').textContent=be?'實際首次打平 '+be.n+' 家':'範圍內實際未打平';document.getElementById('care-current-scale').textContent=x.n+' 家 / '+fmt(x.Q)+' 案';document.getElementById('care-scale-summary').innerHTML=`<strong>實際月損益 ${fmt(shown.profit)} 元</strong> · 平均趨勢估算 ${fmt(trend)} 元<br><small>深綠實線看平均趨勢，淡紫虛線保留增設單元的成本跳降；圓點及打平門檻以實際配置為準。橘點表示超出所填安全量能。</small>`;
document.getElementById('care-scale-chart').innerHTML=dualPlot(data,{axis:x.n,profit:shown.profit},'診所數',[1,50,100,150,200]);}

window.careModel={calc,first,defs,read,at,average,draw,render};render();
})();
