'use strict';
const el=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rich(s){return esc(s).replace(/https?:\/\/[^\s<]+/g,u=>`<a href="${u}" target="_blank" rel="noopener noreferrer">閱讀原始來源 ↗</a>`).replace(/\n/g,'<br>')}
function parts(s){const i=s.indexOf('\n');return i<0?[s,'']:[s.slice(0,i),s.slice(i+1).trim()]}
function blocks(s){s=String(s??'').trim();const a=s.split(/(?:^|\n)\s*\d+[.．、]\s*/);return {intro:a.length>1?a.shift().trim():'',items:a.length?a.filter(x=>x.trim()).map(x=>x.trim()):[]}}
function dateKey(c){if(!c)return null;const s=String(c.v??'');let m=s.match(/^Date\((\d+),(\d+),(\d+)/);if(m)return validDate(+m[1],+m[2]+1,+m[3]);m=String(c.f??c.v??'').match(/^(\d{3,4})[\/\-年](\d{1,2})[\/\-月](\d{1,2})/);if(m)return validDate(+m[1]<1911?+m[1]+1911:+m[1],+m[2],+m[3]);return null}
function validDate(y,m,d){const t=new Date(Date.UTC(y,m-1,d));return t.getUTCFullYear()===y&&t.getUTCMonth()===m-1&&t.getUTCDate()===d?`${y}/${String(m).padStart(2,'0')}/${String(d).padStart(2,'0')}`:null}
function latest(table){if(!table||!Array.isArray(table.rows))throw Error('Google Sheet 沒有可讀取的資料。');const names=['產出日期','本期三項判讀','本週值得讀的兩項發布','三項必要背景閱讀','可直接使用的三個請益問題','文章論述草稿'];const idx=names.map(n=>table.cols.findIndex(c=>String(c.label).trim()===n));if(idx.some(i=>i<0))throw Error('表格欄位已變更，請確認原有六個欄名。');let best=null;for(const row of table.rows){const d=dateKey(row.c[idx[0]]);if(d&&(!best||d>=best.date))best={date:d,fields:idx.slice(1).map(i=>String(row.c[i]?.v??''))}}if(!best)throw Error('找不到有效的產出日期。');return best}
function render(data){const [b,c,d,e,f]=data.fields,j=blocks(b),a=blocks(c),q=blocks(e);el('issue-date').textContent=data.date+' 出刊';document.querySelector('.edition').textContent=data.date+' 期';el('period').textContent=b.split('\n').find(x=>x.startsWith('檢索期間'))||'';el('judgment-title').textContent=`本期判讀 · ${j.items.length} 項`;el('article-count').textContent=String(a.items.length).padStart(2,'0');el('reading-note').textContent=a.intro;el('scope').innerHTML=rich(j.intro);el('judgments').innerHTML=j.items.map((s,i)=>{const [t,v]=parts(s);return `<article class="judgment"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${esc(t)}</h3><p>${rich(v)}</p></article>`}).join('');el('articles').innerHTML=a.items.map((s,i)=>{const [t,v]=parts(s),lines=v.split('\n').filter(Boolean);return `<article class="article"><span class="category">精選 ${String(i+1).padStart(2,'0')}</span><h3>${esc(t)}</h3><p class="meta">${esc(lines.shift()||'')}</p><p class="lead">${rich(lines.shift()||'')}</p><details><summary>展開完整內容與資料來源</summary><div class="detail-body">${lines.map(l=>`<p>${rich(l)}</p>`).join('')}</div></details></article>`}).join('');el('question-list').innerHTML=q.items.map((s,i)=>{const [t,v]=parts(s);return `<article class="question"><h3>${i+1}. ${esc(t)}</h3><p>${rich(v)}</p></article>`}).join('');el('draft').textContent=f||'本期未提供論述草稿。';el('background').innerHTML=rich(d||'本期未提供背景閱讀。');el('content').hidden=false;document.title=`照護動向研究｜${data.date} 週報`}
let running=false,sequence=0,lastSuccess='';
function sync(){if(running)return;running=true;const status=el('sync-status');status.textContent='正在讀取 Google Sheet 最近一期…';el('refresh').disabled=true;const name='careSheetResponse'+(++sequence),script=document.createElement('script');let done=false;const finish=err=>{if(done)return;done=true;clearTimeout(timer);script.remove();window[name]=()=>{};setTimeout(()=>delete window[name],60000);running=false;el('refresh').disabled=false;if(err){status.textContent=(lastSuccess?'更新失敗，目前顯示上次成功讀取的內容（'+lastSuccess+'）。':'目前無法取得最新內容。')+' '+err.message+' 請確認網路與表格的公開唯讀設定後重試。';status.dataset.state='error'}};window[name]=res=>{try{if(res.status!=='ok')throw Error('Google Sheet 回傳讀取錯誤。');render(latest(res.table));lastSuccess=new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false});status.textContent='已同步 · '+lastSuccess+'（台灣時間）｜開啟時及每 5 分鐘更新';status.dataset.state='ok';finish()}catch(e){finish(e)}};script.onerror=()=>finish(Error('連線失敗。'));const timer=setTimeout(()=>finish(Error('讀取逾時。')),CONFIG.timeoutMs);const p=new URLSearchParams({gid:CONFIG.gid,headers:'1',range:'A:F',tqx:`out:json;responseHandler:${name}`,tq:'select *',_ :String(Date.now())});script.src=`https://docs.google.com/spreadsheets/d/${encodeURIComponent(CONFIG.spreadsheetId)}/gviz/tq?${p}`;document.head.appendChild(script)}
el('refresh').addEventListener('click',sync);sync();setInterval(()=>{if(!document.hidden)sync()},CONFIG.refreshMs);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
